// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./src/components/layout/components/header/actionBar.vue')['default']
    Avatar: typeof import('./src/components/layout/components/header/avatar.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    Header: typeof import('./src/components/layout/components/header/header.vue')['default']
    Icon: typeof import('./src/components/ReIcon/src/Icon.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    MenuItem: typeof import('./src/components/layout/components/sidebar/menuItem.vue')['default']
    Sidebar: typeof import('./src/components/layout/components/sidebar/sidebar.vue')['default']
    TagView: typeof import('./src/components/layout/components/header/tagView.vue')['default']
  }
}

export { }
